# Generated by Django 6.1 on 2026-09-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi / الاثنين'), (1, 'Mardi / الثلاثاء'), (2, 'Mercredi / الأربعاء'), (3, 'Jeudi / الخميس'), (4, 'Vendredi / الجمعة'), (5, 'Samedi / السبت'), (6, 'Dimanche / الأحد')], unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150)),
                ('description_fr', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.CharField(blank=True, max_length=255)),
                ('price_tnd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_package', models.BooleanField(default=False, help_text='Highlight as a featured package/forfait')),
                ('old_price_tnd', models.DecimalField(blank=True, decimal_places=2, help_text='Optional strike-through price, used for packages/promos', max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Used as the filter key, e.g. 'visage'", unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NOON Center', max_length=100)),
                ('tagline_fr', models.CharField(default='Votre moment de beauté et de sérénité', max_length=200)),
                ('tagline_ar', models.CharField(default='لحظتك الخاصة من الجمال والهدوء', max_length=200)),
                ('about_fr', models.TextField(default='')),
                ('about_ar', models.TextField(default='')),
                ('founder_name', models.CharField(default='Saloua Nejah', max_length=100)),
                ('founded_year', models.PositiveIntegerField(default=2015)),
                ('address_fr', models.CharField(default='Rue Ahmed Amine, Boumhel El Bassatine, Ben Arous — en face de la BIAT', max_length=255)),
                ('address_ar', models.CharField(default='نهج أحمد أمين، بومهل البساتين، بن عروس — مقابل بنك BIAT', max_length=255)),
                ('phone', models.CharField(default='+21629909099', max_length=30)),
                ('whatsapp', models.CharField(default='+21629909099', max_length=30)),
                ('facebook_url', models.URLField(default='https://www.facebook.com/nooncenter2016/')),
                ('map_query', models.CharField(default='Boumhel El Bassatine, Ben Arous, Tunisia', max_length=255)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_fr', models.CharField(default='Cliente NOON Center', max_length=100)),
                ('author_ar', models.CharField(default='زبونة مركز NOON', max_length=100)),
                ('text_fr', models.TextField()),
                ('text_ar', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('service_label', models.CharField(blank=True, help_text='Fallback text if service is deleted/unset', max_length=200)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية')], default='fr', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'En attente / قيد الانتظار'), ('confirmed', 'Confirmé / مؤكد'), ('cancelled', 'Annulé / ملغى'), ('done', 'Terminé / منجز')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory'),
        ),
    ]
