# Generated by Django 6.1.1 on 2026-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_label',
            field=models.CharField(blank=True, help_text='One or more requested services', max_length=500),
        ),
    ]
