# Generated by Django 6.1.1 on 2026-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_service_label_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Max people bookable per time slot for this category'),
        ),
    ]
