# Generated by Django 4.2.30 on 2026-09-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicecategory_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category_slugs',
            field=models.CharField(blank=True, default='', help_text='Comma-separated category slugs for per-category availability', max_length=300),
        ),
    ]
