# Generated by Django 4.2.30 on 2026-09-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_category_slugs_to_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category_times',
            field=models.JSONField(blank=True, default=dict, help_text='Preferred time per category slug, e.g. {"coiffure": "10:00", "spa": "14:00"}'),
        ),
    ]
