# Generated by Django 4.2.30 on 2026-09-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_category_times_to_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='quality_intro_ar',
            field=models.TextField(default='', help_text='Qualité section intro text (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quality_intro_fr',
            field=models.TextField(default='', help_text='Qualité section intro text (French)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quality_points_ar',
            field=models.TextField(default='', help_text='Qualité bullet points (Arabic), one per line'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quality_points_fr',
            field=models.TextField(default='', help_text='Qualité bullet points (French), one per line'),
        ),
    ]
