# Generated by Django 4.2.30 on 2026-09-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_quality_fields_to_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='quality_intro_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='quality_intro_fr',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='quality_points_ar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='quality_points_fr',
        ),
    ]
