# Generated by Django 4.2.30 on 2026-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_quality_fields_from_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
