# Generated by Django 6.1.1 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Typical duration of one appointment in this category, in minutes (used to chain consecutive bookings)'),
        ),
    ]