# Generated by Django 6.1.1 on 2026-09-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, help_text='Business coordinates (WGS84), e.g. 36.7248. Used for the interactive map card.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, help_text='Business coordinates (WGS84), e.g. 10.2920. Used for the interactive map card.', max_digits=9, null=True),
        ),
    ]
