# Generated by Django 6.1.1 on 2026-09-19 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_latitude_sitesettings_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Machine-readable action name, e.g. 'gallery_uploaded'", max_length=60)),
                ('target_type', models.CharField(blank=True, default='', help_text="Target model name, e.g. 'gallery', 'booking', 'settings'", max_length=50)),
                ('target_key', models.CharField(blank=True, default='', help_text='Human readable target reference (id or title)', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity log entry',
                'verbose_name_plural': 'Activity log entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
