# Generated by Django 4.2.30 on 2026-09-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Promu(e) admin depuis le tableau de bord. Seul le super admin peut modifier ce champ.'),
        ),
    ]
