# Generated by Django 4.2.30 on 2026-09-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_add_client_account_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Lien vers le compte Django (login email + mot de passe) de ce·tte admin promu·e.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
