# Generated by Django 4.2.30 on 2026-09-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clientaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founder_photo',
            field=models.ImageField(blank=True, help_text='Photo optionnelle de la fondatrice pour la carte "Notre histoire".', null=True, upload_to='founder/'),
        ),
    ]
