# Generated by Django 4.2.30 on 2026-09-26 23:30

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def hash_existing_codes(apps, schema_editor):
    PhoneVerification = apps.get_model('core', 'PhoneVerification')
    for verification in PhoneVerification.objects.all().iterator():
        verification.code = make_password(verification.code)
        verification.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_testimonial_text_ar_alter_testimonial_text_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='code',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(hash_existing_codes, migrations.RunPython.noop),
    ]
