# Generated by Django 4.2.30 on 2026-09-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_hash_phone_verification_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
