# Generated by Django 4.2.30 on 2026-09-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_refresh_phone_verification_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
