# Generated by Django 4.2.30 on 2026-09-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_phone_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
