# Generated by Django 4.2.30 on 2026-09-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_client_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='session_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
