# Generated by Django 6.1.2 on 2026-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_client_session_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the service, in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_is_from',
            field=models.BooleanField(default=False, help_text='Show the price as « à partir de »'),
        ),
    ]
